### ISSUE TITLE
Please enable Tute annotation access via Google Could Storage

### ISSUE THREAD

**Issue by pgrosu** [googlegenomics/bigquery-examples#24]
Hi Nicole,

Thank you for adding this feature, but I'm getting the following access error:

```
$ gsutil ls gs://tute_db
AccessDeniedException: 403 Forbidden
$
```
This is based on the following provided link:

https://docs.google.com/document/d/1_Kryc4qAqw1NRezaqDJ1tXUSCbxEkKK4SSi_kZuyHtU/pub

Thanks,
Paul

**Comment by deflaux** [comment]
Hi Paul,

This very cool resource is provided by Tute Genomics, so please be sure to send any requests or feedback about it to tute-genomics@googlegroups.com

Thanks!
Nicole

**Comment by pgrosu** [comment]
Aha!  Will do :)

Thanks Nicole,
Paul
