### ISSUE TITLE
Schema link is broken

### ISSUE THREAD

**Issue by gideonite** [googlegenomics/bigquery-examples#27]
When I click the schema link I get sent to the BigQuery web interface but with no result. It would be really helpful to be able to view the schema.

Here is a screenshot of what I see:

![2015-08-15-19 23 53_1366x768_scrot](https://cloud.githubusercontent.com/assets/2163686/9291261/6cbde59c-4383-11e5-8600-819fb8e81bef.png)

Probably not relevant, but I check the JavaScript console and there were no errors.

Thanks for the help!

**Comment by deflaux** [comment]
Thanks for filing this issue.  Have you been able to view the schema successfully yet?  I definitely want to understand what needs to change (update documentation, fix a bug, etc...) so that the schema can be viewed successfully right away.

Also, by the way, checkout http://googlegenomics.readthedocs.org/ for more documentation about public data and genomics github samples.

**Comment by gideonite** [comment]
I have been able to successfully view the schema via the BigQuery commandline tool:

```
bq show genomics-public-data:1000_genomes.variants
```

With that said, there are no descriptions of what the fields mean. Many of the fields are documented in various VCF file descriptions and 1000 Genomes documentation, but I can't find what `reference_name` means. It probably makes sense to copy over the field descriptions so that everything is at your fingertips, as with some of the other public datasets.

AFAIU, the only way to view a schema via the BigQuery web interface is by clicking through the dataset's dropdown menu on the left of the web interface. However, this brings up the question of how to include The 1000 Genomes Project into my personal dashboard. It is not listed as one of the publicly available datasets, and aside from those, it appears that the only way to interact with data via the web interface is by uploading your own.

So the question is, how do I add the 1000 Genomes Project to my BigQuery web dashboard?

**Comment by gideonite** [comment]
This discussion is more active on Google Groups here: https://groups.google.com/forum/#!topic/google-genomics-discuss/Ipjpe0P81qo.
