### ISSUE TITLE
Consider using the full version of ClinVar

### ISSUE THREAD

**Issue by jaredroach** [googlegenomics/bigquery-examples#6]
The current full version appears to be here: ftp://ftp.ncbi.nlm.nih.gov//pub/clinvar/xml/ClinVarFullRelease_2014-05.xml.gz
This version seems to contain the RCV records and their fields. These RCV records better enable linking between the ClinVar variants and search terms such as "Bipolar".
The tab-delimited downloads (e.g., ftp://ftp.ncbi.nlm.nih.gov//pub/clinvar/tab_delimited/variant_summary.txt.gz) don't seem to have all the necessary fields for linking.

**Comment by deflaux** [comment]
Tute Genomics has provided a nice import of ClinVar https://github.com/googlegenomics/bigquery-examples/commit/56e04b4c67e65a265d945ffe5eeca0bbe1bb053e
